AWSTemplateFormatVersion: '2010-09-09'
Description: Day 5 - Destination S3 bucket for CRR (us-east-1)

Parameters:
  BucketName:
    Type: String
  ReplicationRoleArn:
    Type: String
    Default: ""

Conditions:
  HasRole: !Not [!Equals [!Ref ReplicationRoleArn, ""]]

Resources:
  DestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules: [{ ObjectOwnership: BucketOwnerEnforced }]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 }

  DestBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: HasRole
    Properties:
      Bucket: !Ref DestBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowReplicationFromSourceRole
            Effect: Allow
            Principal: { AWS: !Ref ReplicationRoleArn }
            Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicateTags
              - s3:ObjectOwnerOverrideToBucketOwner
            Resource: !Sub arn:aws:s3:::${BucketName}/*
Outputs:
  DestBucketName: { Value: !Ref DestBucket }
  DestBucketArn:  { Value: !GetAtt DestBucket.Arn }